# Generated by Django 3.2.3 on 2021-06-27 05:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('emailid', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=10)),
                ('photo', models.ImageField(blank=True, upload_to='pics/')),
            ],
        ),
        migrations.CreateModel(
            name='Violators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='unknown', max_length=10)),
                ('pic', models.FileField(upload_to='violators/')),
                ('usn', models.ForeignKey(default='UNKNOWN', null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.studentdetails')),
            ],
        ),
    ]
